# Doom thing data.
THING_DOOM_X = 0
THING_DOOM_Y = 1
THING_DOOM_ANGLE = 2
THING_DOOM_TYPE = 3
THING_DOOM_FLAGS = 4

# Hexen thing data.
THING_HEXEN_ID = 0
THING_HEXEN_X = 1
THING_HEXEN_Y = 2
THING_HEXEN_Z = 3
THING_HEXEN_ANGLE = 4
THING_HEXEN_TYPE = 5
THING_HEXEN_FLAGS = 6
THING_HEXEN_ACTION = 7
THING_HEXEN_ARG0 = 8
THING_HEXEN_ARG1 = 9
THING_HEXEN_ARG2 = 10
THING_HEXEN_ARG3 = 11
THING_HEXEN_ARG4 = 12

# Common thing flags.
THING_FLAG_EASY = 0x0001
THING_FLAG_MEDIUM = 0x0002
THING_FLAG_HARD = 0x0004
THING_FLAG_AMBUSH = 0x0008

# Doom thing flags.
THING_FLAG_DOOM_NOTSINGLE = 0x0010
THING_FLAG_DOOM_NOTDM = 0x0020
THING_FLAG_DOOM_NOTCOOP = 0x0040

# Hexen thing flags.
THING_FLAG_HEXEN_DORMANT = 0x0010
THING_FLAG_HEXEN_FIGHTER = 0x0020
THING_FLAG_HEXEN_CLERIC = 0x0040
THING_FLAG_HEXEN_MAGE = 0x0080
THING_FLAG_HEXEN_SP = 0x0100
THING_FLAG_HEXEN_COOP = 0x0200
THING_FLAG_HEXEN_DM = 0x0400

# Nodes data.
NODE_X = 0
NODE_Y = 1
NODE_DELTA_X = 2
NODE_DELTA_Y = 3
NODE_BBRIGHT_TOP = 4
NODE_BBRIGHT_BOTTOM = 5
NODE_BBRIGHT_LEFT = 6
NODE_BBRIGHT_RIGHT = 7
NODE_BBLEFT_TOP = 8
NODE_BBLEFT_BOTTOM = 9
NODE_BBLEFT_LEFT = 10
NODE_BBLEFT_RIGHT = 11
NODE_CHILD_RIGHT = 12
NODE_CHILD_LEFT = 13

# Node index is a subsector.
NODE_FLAG_SUBSECTOR = 0x8000

# Segment data.
SEGMENT_VERTEX_START = 0
SEGMENT_VERTEX_END = 1
SEGMENT_ANGLE = 2
SEGMENT_LINEDEF = 3
SEGMENT_SIDE = 4
SEGMENT_OFFSET = 5

# Subsector data.
SUBSECTOR_SEG_COUNT = 0
SUBSECTOR_FIRST_SEG = 1

# Sector data.
SECTOR_FLOORZ = 0
SECTOR_CEILZ = 1
SECTOR_FLOORTEX = 2
SECTOR_CEILTEX = 3
SECTOR_LIGHTLEVEL = 4
SECTOR_SPECIAL = 5
SECTOR_TAG = 6

# Sidedef data.
SIDEDEF_OFFSETX = 0
SIDEDEF_OFFSETY = 1
SIDEDEF_TEXTURE_UPPER = 2
SIDEDEF_TEXTURE_LOWER = 3
SIDEDEF_TEXTURE_MIDDLE = 4
SIDEDEF_SECTOR = 5

# Common linedef data.
LINEDEF_VERTEX_1 = 0
LINEDEF_VERTEX_2 = 1
LINEDEF_FLAGS = 2

# Doom linedef data.
LINEDEF_DOOM_TYPE = 3
LINEDEF_DOOM_TAG = 4
LINEDEF_DOOM_SIDEDEF_FRONT = 5
LINEDEF_DOOM_SIDEDEF_BACK = 6

# Hexen linedef data.
LINEDEF_HEXEN_ACTION = 3
LINEDEF_HEXEN_ARG0 = 4
LINEDEF_HEXEN_ARG1 = 5
LINEDEF_HEXEN_ARG2 = 6
LINEDEF_HEXEN_ARG3 = 7
LINEDEF_HEXEN_ARG4 = 8
LINEDEF_HEXEN_SIDEDEF_FRONT = 9
LINEDEF_HEXEN_SIDEDEF_BACK = 10

# Common linedef flags.
LINEDEF_FLAG_IMPASSIBLE = 0x0001
LINEDEF_FLAG_BLOCKMONSTERS = 0x0002
LINEDEF_FLAG_TWOSIDED = 0x0004
LINEDEF_FLAG_UPPERUNPEG = 0x0008
LINEDEF_FLAG_LOWERUNPEG = 0x0010
LINEDEF_FLAG_SECRET = 0x0020
LINEDEF_FLAG_BLOCKSOUND = 0x0040
LINEDEF_FLAG_DONTDRAW = 0x0080
LINEDEF_FLAG_ALWAYSDRAW = 0x0100

# Hexen linedef flags.
LINEDEF_FLAG_HEXEN_REPEATEDUSE = 0x0200
LINEDEF_FLAG_HEXEN_PLAYERUSE = 0x0400
LINEDEF_FLAG_HEXEN_MONSTERCROSS = 0x0800
LINEDEF_FLAG_HEXEN_PROJECTILEUSE = 0x0C00
LINEDEF_FLAG_HEXEN_PLAYERBUMP = 0x1000
LINEDEF_FLAG_HEXEN_PROJECTILECROSS = 0x1400
LINEDEF_FLAG_HEXEN_PLAYERUSE_PASSTHROUGH = 0x1800
LINEDEF_FLAG_HEXEN_PLAYERSANDMONSTERS = 0x2000
LINEDEF_FLAG_HEXEN_UNUSED = 0x4000
LINEDEF_FLAG_HEXEN_BLOCKALL = 0x8000

# Vertex data.
VERTEX_X = 0
VERTEX_Y = 1

# Unused sidedef indicator.
SIDEDEF_NONE = 0xffff

# 3D floor line special flag values.
THREED_KIND_SOLID = 0x01
THREED_KIND_SWIMMABLE = 0x02
THREED_KIND_NONSOLID = 0x04
THREED_FLAG_IGNORE_BOTTOM = 0x08