DIRECTION_UP = 0
DIRECTION_RIGHT = 1
DIRECTION_DOWN = 2
DIRECTION_LEFT = 3
DIRECTION_RANGE = [DIRECTION_UP, DIRECTION_RIGHT, DIRECTION_DOWN, DIRECTION_LEFT]

FLAG_DAMAGE_LOW = 0x0001
FLAG_DAMAGE_MEDIUM = 0x0002
FLAG_DAMAGE_HIGH = 0x0004
FLAG_JUMP_NORTH = 0x0008
FLAG_JUMP_EAST = 0x0010
FLAG_JUMP_SOUTH = 0x0020
FLAG_JUMP_WEST = 0x0040

AREA_SIZE_MAX = 384
AREA_SIZE_RATIO = 128

SIDE_TOP = 0
SIDE_RIGHT = 1
SIDE_BOTTOM = 2
SIDE_LEFT = 3
SIDE_RANGE = [SIDE_TOP, SIDE_RIGHT, SIDE_BOTTOM, SIDE_LEFT]
SIDE_RANGE_OPPOSITE = [SIDE_BOTTOM, SIDE_LEFT, SIDE_TOP, SIDE_RIGHT]